apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-config
data:
    APP_ENV: {{ .Values.environment.APP_ENV | quote }}
    LOG_LEVEL: {{ .Values.environment.LOG_LEVEL | quote }}
    FEATURE_FLAG: "true"
