 apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}
        spec:
            containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
              - containerPort: 80

              # Environment variables from ConfigMap
              envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-config

              # Environment variables from secret
              env:
              - name: DB_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mysql-secret
                        key: MYSQL_ROOT_PASSWORD

              volumeMounts:
              - name: config-volume
                mountPath: /app/config
            volumes:
            - name: config-volume
              configMap:
                  name: {{ .Release.Name }}-config
